service: apiRestServerlessCer

frameworkVersion: '2'

custom:
  bucket: charts-app

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true
  role: arn:aws:iam::596519677648:role/CerV2
  rolePermissionsBoundary: arn:aws:iam::596519677648:role/CerV2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  app:
    handler: "./src/app.handler"
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
    environment:
      BUCKET: ${self:custom.bucket}

plugins:
  - serverless-plugin-typescript
  - serverless-offline